### ISSUE TITLE
Transfer SampleSheet.csv to Nestor 

### ISSUE THREAD

**Issue by vezzi** [SciLifeLab/pm#39]

**Comment by guillermo-carrasco** [comment]
Just a matter of adding this in the configuration file, done:

```yaml
    sync:
        ...
        include:
            ...
            - ".csv"
```
