### ISSUE TITLE
pm is not logging to a file

### ISSUE THREAD

**Issue by guillermo-carrasco** [SciLifeLab/pm#44]
Even though it is specified in the configuration file:

```yaml
# This section overrides the default login parameters in Cement
log.logging:
    file: /home/hiseq.bioinfo/log/pm.log
    rotate: True
```
